config/routes.rb
Sample::Application.routes.draw do
  

  get "courses/index"

  get "courses/find1"

  get "courses/find"

  get "students/find"

  get "students/find1"

  get "courses/show"

  get "charts/index"

  get "charts/new"

  get "charts/show"

  get "cricones/index"

  get "cricones/shown"

  get "maps/show"

  get "students/index"

  get "students/show"

  get "students/searching"
  
  get "students/search"

  get "students/new"

  match '/calendars(/:year(/:month))' => 'calendars#index', :as => :calendars, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  get "admissions/home"

  get "admissions/new"

  get "admissions/show"

  get "admissions/edit"

    get "admissions/contactus"
  

  resources :cricones

  resources :admissions

  resources :students

  devise_for :teachers

   resources :courses

 root :to => "admissions#index"

   match ':controller(/:action(/:id(.:format)))'
   
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, :presence =>true
 validates :student_id, :presence =>true
  validates :standard, :presence =>true
  validates :conduct, :presence =>true
validates :course, :presence =>true
   has_attached_file :avatar
  # , :styles => { :medium => "300x300>", :thumb => "100x100>" }
    has_many :courses_students
    has_many :courses, :through => :courses_students


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_filter :authenticate_teacher!
  
  def index
    @student=Student.all
  end

  def show
    @student=Student.find(params[:id])
  end

  def searching
    @max=Student.find(:all,:conditions=>['name LIKE ?',"#{params[:name]}%"])
  end

  def new
    @student=Student.new
    @course=Course.all
  end

  def create
    @course=Course.all
    @student = Student.new(params[:student])
    @student.save
    redirect_to :action=>'index'
  end

  def search
    #@max=Student.find(:all,:conditions=>['student_id LIKE ?',"#%{params[:student_id]}%"])
  end

def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to :action=>'index'
 end
 
def find1
  @st=Student.find(:all)
end

def find
  @course=Course.find_all_by_course_name(params[:id])

end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_student.html.erb
<%= form_for (@student) do |st| %>

<%= st.label :name %>*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:
<%= st.text_field :name %>
    <br/><br/>
    
<%= st.label :studentid %>*&nbsp;&nbsp;:
<%= st.text_field :student_id %>
    <br/><br/>

<%= st.label :standard %>*&nbsp;&nbsp;&nbsp;:
<%=  st.select(:standard, options_for_select([[1, 1], [2, 2],[3, 3],[4, 4],[5, 5],[6,6],[7,7],[8,8],[9,9],[10,10],[11,11],[12,12]])) %>

    <br/><br/>


    <%= st.label :avatar %>&nbsp;&nbsp;&nbsp;:
    <%= st.file_field :avatar %>

    <br/><br/>

<%= st.label :course %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:
<%= st.select(:course, options_for_select([['MPC','MPC'],['BiPC','BiPC'],['MEC','MEC'],['CEC','CEC'],['Others','Others']])) %>


  <br/><br/>

<%= st.label :rank %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:
<%= st.text_field :rank %>
    <br/><br/>

<%= st.label :conduct %>*&nbsp;&nbsp;&nbsp;&nbsp;:
<%= st.text_field :conduct %>
    <br/><br/>

<br/> <br/> <br/>
    <%= st.submit %>

<% end %>

app/views/students/find.html.erb
<% @course.each do |course| %>
<%= course.course_name :id=>course.course_name%>
<br/><br/><%end%>

app/views/students/find1.html.erb
<% @st.each do |course| %>
<%= link_to course.name, :controller=>'students', :action=>'find', :id=>course.name %><br/>
<%end%>

app/views/students/index.html.erb
<center><h3>Listing Students</h3>

<table border="1">
  <tr>
    <th>Student Name</th>
    <th>Student ID</th>
    <th>Standard</th>
        <th>Course</th>
    <th>Rank</th>
    <th>Conduct</th>
    <th></th>
   <th></th>

  </tr>
 <tr>
<% @student.each do |student| %>
    <td><%= student.name %></td>
    <td><%= student.student_id %></td>
    <td><%= student.standard %></td>
    <td><%= student.course %></td>
    <td><%= student.rank %></td>
    <td><%= student.conduct %></td>


    <td><%= link_to 'Show', student %>
    </td>

    <td><%= link_to 'Delete',student, :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>

</table><br/><br/>



<%= link_to 'New Student Form', :controller=>'students', :action=>'new' %><br/><br/>
<%= link_to 'Search Student', :controller=>'students', :action=>'search' %><br/><br/>
<%= link_to 'Student courses', :controller=>'students', :action=>'find1' %><br/><br/>
<%= link_to 'Back', :controller=>'admissions', :action=>'index' %><br/></center>

app/views/students/new.html.erb
<h2>New Student Details:</h2>


<%= render 'student' %>

<center><%= link_to 'Back', :controller=> 'students', :action=> 'index' %>
</center>

app/views/students/search.html.erb
<h3>Searching for a student...</h3>
  <br/><br/><br/>


<center><%= form_tag :controller => 'students', :action => 'searching', :method => 'get' do %>
      <%= text_field_tag :name, params[:name], :id => 'name' %>
    <%= submit_tag "Search", :name => nil %>
  <% end %><br/><br/>
<a href="index">Back</a></center>

app/views/students/searching.html.erb
<%#= will_paginate @student %>


<center><%if (@max.length==0)%>
<p><br/><br/><h3>There are no student matching to your entered text..<br/> Enter the student name correctly..</h3></p>
</center><%else%>
<p align="left"/p><b>Searched Results...</b>
<% @max.each do |w| %>
<p align="left"/p> <br/><strong>
          <b>student name:</b>&nbsp;&nbsp;<%= w.name%></strong><br/>
          <b>student id:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= w.student_id%><br/>
          <b>standard:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<%= w.standard%> class<br/>
          <b>Rank:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= w.rank%>rank<br/>
          <b>Conduct:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=  w.conduct%> <br/></p>
       
<%end%>
<%end%>
<center><a href="search">Back</a></center>

app/views/students/show.html.erb
</br>

<%= image_tag @student.avatar.url %>

<p>
  <b>Student Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Student_id:</b>
  <%= @student.student_id %>
</p>

<p>
  <b>Course:</b>
  <%= @student.course %>
</p>



<p>
  <b>Standard:</b>
  <%= @student.standard %> Class
</p>

<p>
  <b>Rank:</b>
  <%= @student.rank %>
</p>

<p>
  <b>Conduct:</b>
  <%= @student.conduct %>
</p>


<%= link_to 'Back', students_path %>